"""тест 2

Revision ID: 58d9e40b0ef7
Revises: bf922c0fd172
Create Date: 2023-04-11 09:13:00.341402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d9e40b0ef7'
down_revision = 'bf922c0fd172'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
