"""тест1 миграции

Revision ID: bf922c0fd172
Revises: 5a6f833c6338
Create Date: 2023-04-11 07:45:42.509324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf922c0fd172'
down_revision = '5a6f833c6338'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_keys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('binance_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('binance_secret', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='api_keys_pkey'),
    sa.UniqueConstraint('binance_key', name='api_keys_binance_key_key'),
    sa.UniqueConstraint('binance_secret', name='api_keys_binance_secret_key')
    )
    # ### end Alembic commands ###
